{% set name = "forbiddenfruit" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/forbiddenfruit-{{ version }}.tar.gz
  sha256: e3f7e66561a29ae129aac139a85d610dbf3dd896128187ed5454b6421f624253

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - forbiddenfruit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/clarete/forbiddenfruit
  summary: Patch python built-in objects
  description: |
    This project aims to help you reach heaven while writing tests, but it may lead you to hell if used on production code.
    It basically allows you to patch built-in objects, declared in C through python.
  license: LGPL-3.0-only OR MIT
  license_family: Other
  license_file:
    - COPYING
    - COPYING.mit
  doc_url: https://clarete.li/forbiddenfruit/
  dev_url: https://github.com/clarete/forbiddenfruit

extra:
  recipe-maintainers:
    - aymondebroglie
